### ISSUE TITLE
Absolutely amazing!

### ISSUE THREAD

**Issue by davyd-ziarmand** [KobaltBlu/KotOR.js#19]
Great work man, am I right, that you trying to rebuild game engine and then remake kotor on it, but in web? Dont stop! This is very cool project

**Comment by davyd-ziarmand** [comment]
@KobaltBlu

**Comment by davyd-ziarmand** [comment]
what you work on now? maybe you need help?

**Comment by KobaltBlu** [comment]
>Great work man, am I right, that you trying to rebuild game engine and then remake kotor on it, but in web? Dont stop! This is very cool project

> what you work on now? maybe you need help?

Thank you! I deeply appreciate your feedback on the state of the project. It's been a long road to get here and there are still many things to be done to achieve 100% playable status. I am always open to contributions to the project and if you ever felt so inclined, I would welcome any help you had to offer.

Yes, you are correct that the goal of the project is to build an engine that is capable of emulating what the Odyssey Engine did for the KotOR games. This has been a hefty challenge at times due to nothing really being known about the Odyssey Engine other than its similarities to the Aurora Engine that preceded it.

As someone who has been modding and hacking these games since they came out, I can assure you that you don't have to worry about me going anywhere anytime soon. This project has been a great way for me to apply and learn new skills, all while finding a new way to appreciate the games that made such an impact on me back in the day.

At the moment, my main focus is wrapped up in the combat refactor branch. The combat engine has needed a lot of work for a long time. It is still very much a WIP so there is room for help there. There are still some NWScript functions that have not been written yet. There is also room for improvement in the game loop as well. 

KotOR Forge is still behind a bit since the conversion over to typescript. Some of the functionality needs to be reincorporated back into the file editors and such. Some file formats can be opened, but not edited for instance.

Documentation is also nonexistent at this time. I plan on incorporating TSDoc notifiers to flesh out the docs for any of the code files. There is also a need for documentation on KotOR Forge and how to use it effectively.

There is still a lot of meat left on the bone for anyone to jump in and make noticeable contributions to the project.
